monolog:
    channels:
        - deprecation # custom channel for deprecations

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]
            deprecation:
                type: stream
                path: "%kernel.logs_dir%/deprecations.log"
                level: debug
                channels: [deprecation]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: rotating_json
                buffer_size: 50
                channels: ["!event"]

            rotating_json:
                type: rotating_file
                path: "%kernel.logs_dir%/prod.log"
                max_files: 7 # Keep last 7 log files
                level: info
                formatter: monolog.formatter.json
                channels: ["!event"]

            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]

            deprecation:
                type: stream
                path: "%kernel.logs_dir%/deprecations.log"
                level: warning
                channels: [deprecation]
                formatter: monolog.formatter.json
